# Inputs and Outputs

**NOTE: Typically we will just be either reading csv files directly or using pandas-datareader to pull data from the web. Consider this lecture just a quick overview of what is possible with pandas (we won't be working with SQL or Excel files in this course)**

## Data Input and Output

This notebook is the reference code for getting input and output, pandas can read a variety of file types using its pd.read_ methods. Let's take a look at the most common data types:

In [1]:
import numpy as np
import pandas as pd

## Check out the references here! 

**This is the best online resource for how to read/write to a variety of data sources!**

https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html

----
----

<table border="1" class="colwidths-given docutils">
<colgroup>
<col width="12%" />
<col width="40%" />
<col width="24%" />
<col width="24%" />
</colgroup>
<thead valign="bottom">
<tr class="row-odd"><th class="head">Format Type</th>
<th class="head">Data Description</th>
<th class="head">Reader</th>
<th class="head">Writer</th>
</tr>
</thead>
<tbody valign="top">
<tr class="row-even"><td>text</td>
<td><a class="reference external" href="https://en.wikipedia.org/wiki/Comma-separated_values">CSV</a></td>
<td><a class="reference internal" href="#io-read-csv-table"><span class="std std-ref">read_csv</span></a></td>
<td><a class="reference internal" href="#io-store-in-csv"><span class="std std-ref">to_csv</span></a></td>
</tr>
<tr class="row-odd"><td>text</td>
<td><a class="reference external" href="https://www.json.org/">JSON</a></td>
<td><a class="reference internal" href="#io-json-reader"><span class="std std-ref">read_json</span></a></td>
<td><a class="reference internal" href="#io-json-writer"><span class="std std-ref">to_json</span></a></td>
</tr>
<tr class="row-even"><td>text</td>
<td><a class="reference external" href="https://en.wikipedia.org/wiki/HTML">HTML</a></td>
<td><a class="reference internal" href="#io-read-html"><span class="std std-ref">read_html</span></a></td>
<td><a class="reference internal" href="#io-html"><span class="std std-ref">to_html</span></a></td>
</tr>
<tr class="row-odd"><td>text</td>
<td>Local clipboard</td>
<td><a class="reference internal" href="#io-clipboard"><span class="std std-ref">read_clipboard</span></a></td>
<td><a class="reference internal" href="#io-clipboard"><span class="std std-ref">to_clipboard</span></a></td>
</tr>
<tr class="row-even"><td>binary</td>
<td><a class="reference external" href="https://en.wikipedia.org/wiki/Microsoft_Excel">MS Excel</a></td>
<td><a class="reference internal" href="#io-excel-reader"><span class="std std-ref">read_excel</span></a></td>
<td><a class="reference internal" href="#io-excel-writer"><span class="std std-ref">to_excel</span></a></td>
</tr>
<tr class="row-odd"><td>binary</td>
<td><a class="reference external" href="http://www.opendocumentformat.org">OpenDocument</a></td>
<td><a class="reference internal" href="#io-ods"><span class="std std-ref">read_excel</span></a></td>
<td>&#160;</td>
</tr>
<tr class="row-even"><td>binary</td>
<td><a class="reference external" href="https://support.hdfgroup.org/HDF5/whatishdf5.html">HDF5 Format</a></td>
<td><a class="reference internal" href="#io-hdf5"><span class="std std-ref">read_hdf</span></a></td>
<td><a class="reference internal" href="#io-hdf5"><span class="std std-ref">to_hdf</span></a></td>
</tr>
<tr class="row-odd"><td>binary</td>
<td><a class="reference external" href="https://github.com/wesm/feather">Feather Format</a></td>
<td><a class="reference internal" href="#io-feather"><span class="std std-ref">read_feather</span></a></td>
<td><a class="reference internal" href="#io-feather"><span class="std std-ref">to_feather</span></a></td>
</tr>
<tr class="row-even"><td>binary</td>
<td><a class="reference external" href="https://parquet.apache.org/">Parquet Format</a></td>
<td><a class="reference internal" href="#io-parquet"><span class="std std-ref">read_parquet</span></a></td>
<td><a class="reference internal" href="#io-parquet"><span class="std std-ref">to_parquet</span></a></td>
</tr>
<tr class="row-odd"><td>binary</td>
<td><a class="reference external" href="https://msgpack.org/index.html">Msgpack</a></td>
<td><a class="reference internal" href="#io-msgpack"><span class="std std-ref">read_msgpack</span></a></td>
<td><a class="reference internal" href="#io-msgpack"><span class="std std-ref">to_msgpack</span></a></td>
</tr>
<tr class="row-even"><td>binary</td>
<td><a class="reference external" href="https://en.wikipedia.org/wiki/Stata">Stata</a></td>
<td><a class="reference internal" href="#io-stata-reader"><span class="std std-ref">read_stata</span></a></td>
<td><a class="reference internal" href="#io-stata-writer"><span class="std std-ref">to_stata</span></a></td>
</tr>
<tr class="row-odd"><td>binary</td>
<td><a class="reference external" href="https://en.wikipedia.org/wiki/SAS_(software)">SAS</a></td>
<td><a class="reference internal" href="#io-sas-reader"><span class="std std-ref">read_sas</span></a></td>
<td>&#160;</td>
</tr>
<tr class="row-even"><td>binary</td>
<td><a class="reference external" href="https://docs.python.org/3/library/pickle.html">Python Pickle Format</a></td>
<td><a class="reference internal" href="#io-pickle"><span class="std std-ref">read_pickle</span></a></td>
<td><a class="reference internal" href="#io-pickle"><span class="std std-ref">to_pickle</span></a></td>
</tr>
<tr class="row-odd"><td>SQL</td>
<td><a class="reference external" href="https://en.wikipedia.org/wiki/SQL">SQL</a></td>
<td><a class="reference internal" href="#io-sql"><span class="std std-ref">read_sql</span></a></td>
<td><a class="reference internal" href="#io-sql"><span class="std std-ref">to_sql</span></a></td>
</tr>
<tr class="row-even"><td>SQL</td>
<td><a class="reference external" href="https://en.wikipedia.org/wiki/BigQuery">Google Big Query</a></td>
<td><a class="reference internal" href="#io-bigquery"><span class="std std-ref">read_gbq</span></a></td>
<td><a class="reference internal" href="#io-bigquery"><span class="std std-ref">to_gbq</span></a></td>
</tr>
</tbody>
</table>

-----
----

# Reading in a  CSV
Comma Separated Values files are text files that use commas as field delimeters.<br>
Unless you're running the virtual environment included with the course, you may need to install <tt>xlrd</tt> and <tt>openpyxl</tt>.<br>
In your terminal/command prompt run:

    conda install xlrd
    conda install openpyxl

Then restart Jupyter Notebook.
(or use pip install if you aren't using the Anaconda Distribution)

## Understanding File Paths

You have two options when reading a file with pandas:

1. If your .py file or .ipynb notebook is located in the **exact** same folder location as the .csv file you want to read, simply pass in the file name as a string, for example:
    
        df = pd.read_csv('some_file.csv')
        
2. Pass in the entire file path if you are located in a different directory. The file path must be 100% correct in order for this to work. For example:

        df = pd.read_csv("C:\\Users\\myself\\files\\some_file.csv")

#### Print your current directory file path with pwd

In [2]:
%pwd

'c:\\Users\\prajval gupta\\Desktop\\PYTHON_DA_SIG_2026\\Pandas'

#### List the files in your current directory with ls

In [3]:
%ls

 Volume in drive C has no label.
 Volume Serial Number is FA24-F1AC

 Directory of c:\Users\prajval gupta\Desktop\PYTHON_DA_SIG_2026\Pandas

02-07-2026  14:04    <DIR>          .
17-06-2026  18:48    <DIR>          ..
30-06-2026  14:15           749,823 00-Series.ipynb
30-06-2026  15:04           146,053 01-DataFrames.ipynb
30-06-2026  15:12           111,397 02-Conditional-Filtering.ipynb
01-07-2026  14:53           219,970 03-Useful-Methods.ipynb
01-07-2026  15:20            77,709 04-Missing-Data.ipynb
29-06-2026  19:36             3,602 05.1.ipynb
01-07-2026  15:41           219,355 05-Groupby-Operations-and-MultiIndex.ipynb
05-07-2026  14:18            65,481 06-Combining-DataFrames.ipynb
05-07-2026  14:23            35,355 07-Text-Methods.ipynb
05-07-2026  14:41           107,090 08-Time-Methods.ipynb
07-07-2026  13:53            86,553 09-Inputs-and-Outputs.ipynb
17-06-2026  18:59         1,121,810 10-Pivot-Tables.ipynb
21-10-2025  19:07                51 example.csv
21-10-2025  19:07             5,022 example.xlsx
21-10-2025  19:07        25,112,317 hotel_booking_data.csv
21-10-2025  19:07               177 movie_scores.csv
21-10-2025  19:07            17,727 mpg.csv
21-10-2025  19:07             5,022 my_excel_file.xlsx
06-03-2026  18:09             5,065 new_excel_file.xlsx
05-07-2026  14:53                51 new_file.csv
21-10-2025  19:07             5,021 new_workbook.xlsx
21-10-2025  19:07                51 newfile.csv
21-10-2025  19:07            52,132 reshaping_pivot.png
21-10-2025  19:07             5,459 RetailSales_BeerWineLiquor.csv
21-10-2025  19:07             1,320 Sales_Funnel_CRM.csv
21-10-2025  19:07             1,330 sample_table.html
21-10-2025  19:07               555 simple.html
21-10-2025  19:07            18,752 tips.csv
              28 File(s)     28,174,250 bytes
               2 Dir(s)   8,874,217,472 bytes free

-----
#### NOTE! Common confusion point! Take note that all read input methods are called directly from pandas with pd.read_  , all output methods are called directly off the dataframe with df.to_

-------

### CSV Input

In [4]:
df = pd.read_csv('example.csv')

In [5]:
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [6]:
df = pd.read_csv('example.csv',index_col=0)

In [7]:
df

     b   c   d
a
0    1   2   3
4    5   6   7
8    9  10  11
12  13  14  15

In [8]:
df = pd.read_csv('example.csv')

In [9]:
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

### CSV Output

Set index=False if you do not want to save the index , otherwise it will add a new column to the .csv file that includes your index and call it "Unnamed: 0" if your index did not have a name. If you do want to save your index, simply set it to True (the default value).

In [10]:
df.to_csv('new_file.csv',index=False)
csv_content = df.to_csv(index=False)
df.to_csv('new_file.csv', index=False)
print(csv_content)

a,b,c,d
0,1,2,3
4,5,6,7
8,9,10,11
12,13,14,15

## HTML

Pandas can read table tabs off of HTML. This only works if your firewall isn't blocking pandas from accessing the internet!

Unless you're running the virtual environment included with the course, you may need to install <tt>lxml</tt>, <tt>htmllib5</tt>, and <tt>BeautifulSoup4</tt>.<br>
In your terminal/command prompt run:

    conda install lxml
    
    or
    
    pip install lxml
    
Then restart Jupyter Notebook (you may need to restart your computer).
(or use pip install if you aren't using the Anaconda Distribution)

## read_html

### HTML Input

Pandas read_html function will read tables off of a webpage and return a list of DataFrame objects. NOTE: This only works with well defined <table> objects in the html on the page, this can not magically read in tables that are images on a page.

In [11]:
import requests
url = 'https://en.wikipedia.org/wiki/World_population'
# some websites (like Wikipedia) will reject plain urlopen requests with a 403 error
# using a valid User-Agent header typically works around this restriction:
html = requests.get(url, headers={'User-Agent':'Mozilla/5.0'}).text

# pass the downloaded HTML string to pandas
tables = pd.read_html(html)

C:\Users\prajval gupta\AppData\Local\Temp\ipykernel_12552\1385024625.py:8: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

In [ ]:
print(tables[14])

27

In [24]:
print(tables[13])

   Year  World           Asia         Africa       Europe  \
0  2000   6144  3,741 (60.9%)    811 (13.2%)  726 (11.8%)
1  2024   8160  4,810 (58.9%)  1,520 (18.6%)   745 (9.1%)
2  2050   9660  5,280 (54.7%)  2,470 (25.6%)   703 (7.3%)
3  2075  10250  5,100 (49.8%)  3,290 (32.1%)   636 (6.2%)
4  2100  10180  4,610 (45.3%)  3,810 (37.4%)   592 (5.8%)

  Latin Am./ Caribbean Northern America    Oceania
0           522 (8.5%)       312 (5.1%)  31 (0.5%)
1           663 (8.1%)       385 (4.7%)  46 (0.6%)
2           730 (7.6%)       426 (4.4%)  57 (0.6%)
3           698 (6.8%)       452 (4.4%)  66 (0.6%)
4           613 (6.0%)       475 (4.7%)  73 (0.7%)

In [32]:
print(tables[23])

             vteGlobalization  \
0   Journals  Outline Studies
1                     Aspects
2                      Issues
3                      Global
4                       Other
5                    Theories
6            Notable scholars
7                   Economics
8           Political economy
9         Politics/ sociology
10                      Other
11  Category  Business portal

                                   vteGlobalization.1
0                           Journals  Outline Studies
1   Alter-globalization Anti-globalization movemen...
2   Global Balance of trade Capital outflow Capita...
3   Balance of trade Capital outflow Capital fligh...
4   Brain drain reverse Care drain Development aid...
5   Capital accumulation Dependency Development Ea...
6   Economics David Autor Richard Baldwin Ravi Bat...
7   David Autor Richard Baldwin Ravi Batra Jagdish...
8   Samir Amin Giovanni Arrighi Robert W. Cox Andr...
9   Arjun Appadurai Daniele Archibugi K. Anthony A...
10  Noam Chomsky Thomas Friedman Naomi Klein John ...
11                          Category  Business portal

In [12]:
len(tables) #tables

27

### Not Useful Tables
Pandas found 26 tables on that page. Some are not useful:

In [13]:
tables[0]

,Population (in billions),1,1.1,2,2.1,3,3.1,4,4.1,5,...,6,6.1,7,7.1,8,8.1,9,9.1,10,10.1
0,Year,1804,1804,1927,1927,1960,1960,1974,1974,1987,...,1999,1999,2011,2011,2022,2022,2037,2037,2057,2057
1,Years elapsed,—,123,123,33,33,14,14,13,13,...,12,12,12,11,11,15,15,20,20,—

### Tables that need formatting

Some will be misaligned, meaning you need to do extra work to fix the columns and rows:

In [14]:
tables[1].columns

Index(['Region', '2022 (percent)', '2030 (percent)', '2050 (percent)'], dtype='object')

In [15]:
world_pop = tables[1]

In [16]:
world_pop.columns

Index(['Region', '2022 (percent)', '2030 (percent)', '2050 (percent)'], dtype='object')

In [19]:
world_pop = world_pop['World population (millions, UN estimates)[15]'].drop('#', axis=1)

KeyError: 'World population (millions, UN estimates)[15]'

In [ ]:
# Corrected code: Drop the '#' column first, then select the population column
world_pop = world_pop.drop('#', axis=1)['World population (millions, UN estimates)[14]']

KeyError: "['#'] not found in axis"

In [ ]:
# Alternative: Use column position instead of name (after dropping '#', select the first column)
world_pop = world_pop.drop('#', axis=1).iloc[:, 0]

KeyError: "['#'] not found in axis"

In [ ]:
# If the column name still doesn't work, check the current columns
print("Current columns:", world_pop.columns.tolist())

Current columns: ['Region', '2022 (percent)', '2030 (percent)', '2050 (percent)']

In [ ]:
world_pop.columns

Index(['Region', '2022 (percent)', '2030 (percent)', '2050 (percent)'], dtype='object')

In [ ]:
world_pop.columns = ['Countries', '2000', '2015', '2030 Est.']
world_pop = world_pop.drop(11,axis=0)

In [ ]:
world_pop

        Countries  2000  2015 2030 Est.
0        China[B]  1270  1376      1416
1           India  1053  1311      1528
2   United States   283   322       356
3       Indonesia   212   258       295
4        Pakistan   136   208       245
5          Brazil   176   206       228
6         Nigeria   123   182       263
7      Bangladesh   131   161       186
8          Russia   146   146       149
9          Mexico   103   127       148
10    World total  6127  7349      8501

### Tables that are intact

In [ ]:
tables[6]

   Rank      Country  Population  Area (km2)  Density (Pop. per km2)
0     1    Singapore     5703600         710                    8033
1     2   Bangladesh   168870000      143998                    1173
2     3      Lebanon     6855713       10452                     656
3     4       Taiwan    23604265       36193                     652
4     5  South Korea    51780579       99538                     520
5     6       Rwanda    12374397       26338                     470
6     7        Haiti    11577779       27065                     428
7     8  Netherlands    17480000       41526                     421
8     9       Israel     9220000       22072                     418
9    10        India  1364080000     3287240                     415

## Write to html Output

If you are working on a website and want to quickly output the .html file, you can use to_html

In [ ]:
df.to_html('simple.html',index=False)

**read_html** is not perfect, but its quite powerful for such a simple method call!

# Excel Files

Pandas can read in basic excel files (it will get errors if there are macros or extensive formulas relying on outside excel files), in general, pandas can only grab the raw information from an .excel file.

#### NOTE: Requires the openpyxl and xlrd library! Its provided for you in our environment, or simply install with:

    pip install openpyxl
    pip install xlrd
    
Heavy excel users may want to check out this website: https://www.python-excel.org/

You can think of an excel file as a Workbook containin sheets, which for pandas means each sheet can be a DataFrame.

## Excel file input with read_excel()

In [ ]:
## Install required packages
%pip install openpyxl xlrd

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\prajval gupta\appdata\roaming\python\python311\site-packages (3.1.5)
Requirement already satisfied: xlrd in c:\users\prajval gupta\appdata\roaming\python\python311\site-packages (2.0.2)
Requirement already satisfied: et-xmlfile in c:\users\prajval gupta\appdata\roaming\python\python311\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
df = pd.read_excel('my_excel_file.xlsx',sheet_name='First_Sheet',)

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.to_excel('new_excel_file.xlsx',sheet_name='New_Sheet')

In [ ]:
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [ ]:
print(df.to_string(index=False))

 a  b  c  d
 0  1  2  3
 4  5  6  7
 8  9 10 11
12 13 14 15

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       4 non-null      int64
 1   b       4 non-null      int64
 2   c       4 non-null      int64
 3   d       4 non-null      int64
dtypes: int64(4)
memory usage: 260.0 bytes

In [ ]:
df.to_html(index=False)

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th>a</th>\n      <th>b</th>\n      <th>c</th>\n      <th>d</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td>0</td>\n      <td>1</td>\n      <td>2</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <td>4</td>\n      <td>5</td>\n      <td>6</td>\n      <td>7</td>\n    </tr>\n    <tr>\n      <td>8</td>\n      <td>9</td>\n      <td>10</td>\n      <td>11</td>\n    </tr>\n    <tr>\n      <td>12</td>\n      <td>13</td>\n      <td>14</td>\n      <td>15</td>\n    </tr>\n  </tbody>\n</table>'

In [ ]:
print(df.to_string(index=False))

 a  b  c  d
 0  1  2  3
 4  5  6  7
 8  9 10 11
12 13 14 15

In [ ]:
df = df.reset_index(drop=True)

In [ ]:
#df.index.name = None

In [ ]:
"""You're right! No, to_string() is not always required.

For saving to Excel files, use the index=False parameter directly in to_excel():

This works the same way as:

CSV: df.to_csv('file.csv', index=False)
HTML: df.to_html('file.html', index=False)
When to use to_string():

Only when you want to print or display the dataframe as text without the index
Example: print(df.to_string(index=False))
Summary:

Saving to file (Excel, CSV, HTML) → Use index=False parameter
Displaying in notebook as formatted table → Just type df (shows index by default)
Printing as text → Use print(df.to_string(index=False))
So you don't need to_string() for your Excel file—just use index=False parameter in to_excel().

Claude Haiku 4.5 • 1x"""

"You're right! No, to_string() is not always required.\n\nFor saving to Excel files, use the index=False parameter directly in to_excel():\n\nThis works the same way as:\n\nCSV: df.to_csv('file.csv', index=False)\nHTML: df.to_html('file.html', index=False)\nWhen to use to_string():\n\nOnly when you want to print or display the dataframe as text without the index\nExample: print(df.to_string(index=False))\nSummary:\n\nSaving to file (Excel, CSV, HTML) → Use index=False parameter\nDisplaying in notebook as formatted table → Just type df (shows index by default)\nPrinting as text → Use print(df.to_string(index=False))\nSo you don't need to_string() for your Excel file—just use index=False parameter in to_excel().\n\nClaude Haiku 4.5 • 1x"

In [ ]:
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

### What if you don't know the sheet name? Or want to run a for loop for certain sheet names? Or want every sheet?

Several ways to do this: https://stackoverflow.com/questions/17977540/pandas-looking-up-the-list-of-sheets-in-an-excel-file

In [ ]:
# Returns a list of sheet_names
pd.ExcelFile('my_excel_file.xlsx').sheet_names

['First_Sheet']

#### Grab all sheets

In [ ]:
excel_sheets = pd.read_excel('my_excel_file.xlsx',sheet_name=None)

In [ ]:
type(excel_sheets)

dict

In [ ]:
excel_sheets.keys()

dict_keys(['First_Sheet'])

In [ ]:
excel_sheets['First_Sheet']

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

### Write to Excel File

In [ ]:
df.to_excel('example.xlsx',sheet_name='First_Sheet',index=False)

# SQL Connections

#### NOTE: Highly recommend you explore specific libraries for your specific SQL Engine. Simple search for your database+python in Google and the top results should hopefully include an API.

* [MySQL](https://www.google.com/search?q=mysql+python)
* [PostgreSQL](https://www.google.com/search?q=postgresql+python)
* [MS SQL Server](https://www.google.com/search?q=MSSQLserver+python)
* [Orcale](https://www.google.com/search?q=oracle+python)
* [MongoDB](https://www.google.com/search?q=mongodb+python)

Let's review pandas capabilities by using SQLite, which comes built in with Python.

## Example SQL Database (temporary in your RAM)

You will need to install sqlalchemy with:

    pip install sqlalchemy
    
to follow along. To understand how to make a connection to your own database, make sure to review: https://docs.sqlalchemy.org/en/13/core/connections.html

In [ ]:
from sqlalchemy import create_engine

In [ ]:
temp_db = create_engine('sqlite:///:memory:')

### Write to Database

In [ ]:
tables[6]

   Rank      Country  Population  Area (km2)  Density (Pop. per km2)
0     1    Singapore     5703600         710                    8033
1     2   Bangladesh   168870000      143998                    1173
2     3      Lebanon     6855713       10452                     656
3     4       Taiwan    23604265       36193                     652
4     5  South Korea    51780579       99538                     520
5     6       Rwanda    12374397       26338                     470
6     7        Haiti    11577779       27065                     428
7     8  Netherlands    17480000       41526                     421
8     9       Israel     9220000       22072                     418
9    10        India  1364080000     3287240                     415

In [ ]:
pop = tables[6]

In [ ]:
pop.to_sql(name='populations',con=temp_db)

### Read from SQL Database

In [ ]:
# Read in an entire table
pd.read_sql(sql='populations',con=temp_db)

   index  Rank      Country  Population  Area (km2)  Density (Pop. per km2)
0      0     1    Singapore     5703600         710                    8033
1      1     2   Bangladesh   168870000      143998                    1173
2      2     3      Lebanon     6855713       10452                     656
3      3     4       Taiwan    23604265       36193                     652
4      4     5  South Korea    51780579       99538                     520
5      5     6       Rwanda    12374397       26338                     470
6      6     7        Haiti    11577779       27065                     428
7      7     8  Netherlands    17480000       41526                     421
8      8     9       Israel     9220000       22072                     418
9      9    10        India  1364080000     3287240                     415

In [ ]:
# Read in with a SQL Query
pd.read_sql_query(sql="SELECT Country FROM populations",con=temp_db)

       Country
0    Singapore
1   Bangladesh
2      Lebanon
3       Taiwan
4  South Korea
5       Rwanda
6        Haiti
7  Netherlands
8       Israel
9        India

It is difficult to generalize pandas and SQL, due to a wide array of issues, including permissions,security, online access, varying SQL engines, etc... Use these ideas as a starting off point, and you will most likely need to do your own research for your own situation.